server:
  port: 8999
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: Gateway_API_Service
  cloud:
    gateway:
      routes:
        - id: Clothes-service
          uri: 'lb://Clothes-service'
          predicates:
            - Path=/clothes/**